version: '3.1'

services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: react
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    tmpfs:
      - /tmp
