version: '3.1'

services:
  client:
    container_name: gql_client
    build:
      dockerfile: ./client/Dockerfile
    image: wa_client
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
    tmpfs:
      - /tmp

  db:
    container_name: mysql_db_gql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'ian123'
      MYSQL_DATABASE: 'wa'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  server:
    container_name: gql_server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: wa_server
    restart: always
    depends_on:
      - db
    ports:
      - 4000:4000
    volumes:
      - ./server:/usr/src/app

    tmpfs:
      - /tmp
