version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'ian123'
      MYSQL_DATABASE: 'wa'
    ports:
      - '3306:3306'
    networks:
      dev-network:
        ipv4_address: 172.16.238.10

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: wa_server
    restart: always
    depends_on:
      - db
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    networks:
      - dev-network
    tmpfs:
      - /tmp

networks:
  dev-network:
    ipam:
      driver: default
      config:
        - subnet: '172.16.238.0/24'
