version: '3.1'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'ian123'
      MYSQL_DATABASE: 'wa'
    ports:
      - '3306:3306'
    networks:
      - dev-network

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: wa_server
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    networks:
      - dev-network
    tmpfs:
      - /tmp

networks:
  dev-network:
    driver: bridge
